#ifndef PS1_H
#define PS1_H

#if defined(PS1_RENDERER)

static const char* ps1_vs = 
    "#version 330\n"
    "in vec3 vertexPosition;\n"
    "in vec2 vertexTexCoord;\n"
    "in vec3 vertexNormal;\n"
    "in vec4 vertexColor;\n"
    "uniform mat4 mvp;\n"
    "uniform mat4 matModel;\n"
    "uniform float uPrecision = 480.0;\n"
    "out vec4 fragColor;\n"
    "out vec2 fragTexCoord;\n"
    "out vec3 fragPos;\n"
    "out vec3 fragNormal;\n"
    "void main() {\n"
    "    fragColor = vertexColor;\n"
    "    fragTexCoord = vertexTexCoord;\n"
    "    fragPos = (matModel * vec4(vertexPosition, 1.0)).xyz;\n"
    "    fragNormal = normalize((matModel * vec4(vertexNormal, 0.0)).xyz);\n"
    "    vec4 pos = mvp * vec4(vertexPosition, 1.0);\n"
    "    if (pos.w > 0.0) {\n"
    "        vec2 snappedPos = pos.xy / pos.w;\n"
    "        if (pos.w > 0.1) {\n"
    "            snappedPos = floor(snappedPos * uPrecision + 0.5) / uPrecision;\n"
    "        }\n"
    "        pos.xy = snappedPos * pos.w;\n"
    "    }\n"
    "    gl_Position = pos;\n"
    "}\n";

static const char* ps1_fs = 
    "#version 330\n"
    "in vec4 fragColor;\n"
    "in vec2 fragTexCoord;\n"
    "in vec3 fragPos;\n"
    "in vec3 fragNormal;\n"
    "uniform sampler2D texture0;\n"
    "uniform vec4 colDiffuse;\n"
    "uniform vec3 sunDir;\n"
    "uniform vec3 viewPos;\n"
    "uniform float time;\n"
    "uniform vec4 skyCol;\n"
    "out vec4 finalColor;\n"
    "void main() {\n"
    "    vec4 texelColor = texture(texture0, fragTexCoord);\n"
    "    if (texelColor.a < 0.1) discard;\n"
    "    \n"
    "    // Dynamic Lighting (Directional Shadows)\n"
    "    float diff = max(0.0, dot(fragNormal, sunDir));\n"
    "    float ambient = 0.3;\n"
    "    float light = ambient + diff * 0.9;\n"
    "    \n"
    "    vec3 baseColor = texelColor.rgb * fragColor.rgb * colDiffuse.rgb;\n"
    "    vec3 color = baseColor * light;\n"
    "    \n"
    "    // Water logic (Reflective/Vibrant)\n"
    "    bool isWater = (fragColor.a < 0.9 && fragColor.a > 0.1);\n"
    "    if (isWater) {\n"
    "        vec3 viewDir = normalize(viewPos - fragPos);\n"
    "        float fresnel = pow(1.0 - max(0.0, dot(viewDir, vec3(0.0, 1.0, 0.0))), 3.0);\n"
    "        float shimmer = sin(fragPos.x * 1.2 + time * 2.0) * cos(fragPos.z * 1.2 + time * 1.5) * 0.04;\n"
    "        color = mix(color, skyCol.rgb, fresnel * 0.6 + 0.2) + shimmer;\n"
    "        // Specular highlight\n"
    "        vec3 halfDir = normalize(sunDir + viewDir);\n"
    "        float spec = pow(max(0.0, dot(vec3(0.0, 1.0, 0.0), halfDir)), 64.0) * 1.5 * max(0.0, sunDir.y);\n"
    "        color += vec3(spec);\n"
    "    }\n"
    "    \n"
    "    // Vibrancy and Tone Mapping\n"
    "    float sunY = max(0.0, sunDir.y);\n"
    "    color *= mix(vec3(1.2, 0.8, 0.6), vec3(1.0, 1.0, 1.05), sunY);\n"
    "    \n"
    "    // Subtle Saturation boost\n"
    "    float gray = dot(color, vec3(0.299, 0.587, 0.114));\n"
    "    color = mix(vec3(gray), color, 1.25);\n"
    "    \n"
    "    // PS1 color depth\n"
    "    vec4 c = vec4(color, texelColor.a * fragColor.a * colDiffuse.a);\n"
    "    c.rgb = floor(c.rgb * 31.0 + 0.5) / 31.0;\n"
    "    finalColor = c;\n"
    "}\n";

#endif

#endif // PS1_H
